DERIVED_DATA_PATH = "fastlane/DerivedData/"

lane :clean_up do
    clear_derived_data(derived_data_path: DERIVED_DATA_PATH)
end

lane :build do
    gym(
        project: "SimpleLogin/SimpleLogin.xcodeproj",
        scheme: "SimpleLogin",
        derived_data_path: DERIVED_DATA_PATH,
        clean: true,
        export_method: "development"
    )
end

lane :deploy do
    match(type: "appstore", readonly: true)  # Use readonly in CI for security
    gym(
        project: "SimpleLogin/SimpleLogin.xcodeproj",
        scheme: "SimpleLogin",
        export_method: "app-store",
        clean: true
    )
    pilot(
        skip_waiting_for_build_processing: true
    )
end